### PR TITLE
Prefix StyleValue and its subclasses with "CSS"

### PR DESCRIPTION
**Pull request by rjwright**
StyleValue -> CSSStyleValue
CalcLength -> CSSCalcLength
ColorValue -> CSSColorValue
KeywordValue -> CSSKeywordValue
LengthValue -> CSSLengthValue
NumberValue -> CSSNumberValue
PositionValue -> CSSPositionValue
SimpleLength -> CSSSimpleLength
TransformValue -> CSSTransformValue

Do I need to rename the files?

### CODE REVIEW

**Comment by wilddamon** [comment]
It's probably better to rename the files as well. Maybe do it in a new PR for clarity?

**Comment by rjwright** [comment]
> It's probably better to rename the files as well. Maybe do it in a new PR for clarity?

Sounds good. Can we merge this one so I can do the transform components prefixing? Then I will rename files last.

**Comment by wilddamon** [comment]
Actually, I think it'd be clearer to do it class-by-class in the future (including the file renames), but sure.

**Comment by rjwright** [comment]
> Actually, I think it'd be clearer to do it class-by-class in the future (including the file renames), but sure.

Opps. I'm already almost finished the transformation stuff too. Oh well, good to know for the Blink change.

Thanks.

**Pull request merged**
